api/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('staff-list', views.staff_list),
    path('attendance-create', views.attendance_create),
    
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),

    # Avtorizatsiya
    path('log-in/', views.log_in, name='log_in'),
    path('log-out/', views.log_out, name='log_out'),

    # Staff
    path('create-staff', views.create_staff, name='create_staff'),
    path('list-staff', views.list_staff, name='list_staff'),
    path('update-staff/<int:id>/', views.update_staff, name='update_staff'),
    path('delete-staff/<int:id>/', views.delete_staff, name='delete_staff'),

    # Attendance
    path('list-attendance', views.list_attendance, name='list_attendance'),

    # Edit profile
    path('edit-profile/<int:id>/', views.edit_profile, name='edit_profile'),
    
]

main/urls.py
from django.urls import path, include
from . import views
from dashboard.views import log_in

app_name = 'main'

urlpatterns = [
    path('', log_in),
    path('api/', include('api.urls'))
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('dashboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


class Staff(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.first_name
    


class Attendance(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, null=True)
    enter_time = models.DateTimeField(null=True, blank=True)
    exit_time = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:
        return self.staff.first_name


            
            

api/views.py
from main import models 
from . import serializers
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.utils import timezone


@api_view(['GET'])
def staff_list(request):
    staff=models.Staff.objects.all()
    serializer_date = serializers.StaffSerializerList(staff, many=True)

    return Response(serializer_date.data)


@api_view(['POST'])
def attendance_create(request):
    serializer_data = serializers.AttendanceSerializer(data=request.data)
    if serializer_data.is_valid():
        staff = serializer_data.validated_data.get('staff')
        enter_time = serializer_data.validated_data.get('enter_time')
        exit_time = serializer_data.validated_data.get('exit_time')

        if not enter_time:
            enter_time = timezone.now()
            serializer_data.validated_data['enter_time'] = enter_time 

        last_attendance = models.Attendance.objects.filter(staff=staff).last()

        if last_attendance and not exit_time:
            last_attendance.exit_time = enter_time
            last_attendance.save()
        else:
            serializer_data.save()

        return Response({'success': True})
    return Response({'success': False})

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from main import models


# Autentifikatsiya
def log_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard:index')
        else:
            error_message = "Username or password is incorrect"
            return render(request, 'auth/login.html', {'error_message': error_message})
    return render(request, 'auth/login.html')


def log_out(request):
    logout(request)
    return redirect('dashboard:log_in')


# Profilni tahrirlash
@login_required(login_url='dashboard:log_in')
def edit_profile(request, id):
    user = get_object_or_404(User, id=id)
    
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        
        if password:
            new_password = request.POST.get('new_password')
            confirm_password = request.POST.get('confirm_password')
            if new_password == confirm_password:
                user.set_password(new_password)
            else:
                error_message = "Passwords do not match"
                return render(request, 'dashboard/profile.html', {'user': user, 'error_message': error_message})
        
        user.username = username
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        
        return redirect('dashboard:index')
    
    return render(request, 'dashboard/profile.html', {'user': user})


# Admin panel bosh sahifasi
@login_required(login_url='dashboard:log_in')
def index(request):
    user_count = User.objects.count()
    staff_count = models.Staff.objects.count()
    
    context = {
        'user_count': user_count,
        'staff_count': staff_count,
    }
    
    return render(request, 'dashboard/index.html', context)


# Xodimlar
@login_required(login_url='dashboard:log_in')
def create_staff(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        models.Staff.objects.create(first_name=first_name, last_name=last_name)
        return redirect('dashboard:list_staff')
    return render(request, 'dashboard/staff/create.html')


@login_required(login_url='dashboard:log_in')
def list_staff(request):
    staff = models.Staff.objects.all()
    context = {
        'staff': staff,
    }
    return render(request, 'dashboard/staff/list.html', context)


@login_required(login_url='dashboard:log_in')
def update_staff(request, id):
    staff = get_object_or_404(models.Staff, id=id)
    
    if request.method == 'POST':
        staff.first_name = request.POST['first_name']
        staff.last_name = request.POST['last_name']
        staff.save()
        return redirect('dashboard:list_staff')
    
    return render(request, 'dashboard/staff/update.html', {'staff': staff})


@login_required(login_url='dashboard:log_in')
def delete_staff(request, id):
    staff = get_object_or_404(models.Staff, id=id)
    staff.delete()
    return redirect('dashboard:list_staff')


# Kelishlar
@login_required(login_url='dashboard:log_in')
def list_attendance(request):
    attendance = models.Attendance.objects.all()
    context = {
        'attendance': attendance,
    }
    return render(request, 'dashboard/attendance/list.html', context)

main/views.py
from django.shortcuts import render

templates/dashboard/attendance/list.html
{% extends "dashboard/base.html" %}
{% block content %}
<br>
<br>
<br>
<table class="table table-striped dataTable no-footer" id="table-1" role="grid" aria-describedby="table-1_info">
    <thead>                                 
      <tr role="row">
        <th class="text-center sorting_asc" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="#: activate to sort column descending">#</th>
        <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1" aria-label="Task Name: activate to sort column ascending">Xodimlar</th>
        <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1" aria-label="Task Name: activate to sort column ascending">Kirish vaqti</th>
        <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1" aria-label="Task Name: activate to sort column ascending">Chiqish vaqti</th>
        </thead>
    <tbody>                                 
      
        {% for attend in attendance %}
<tr role="row">
    <td>{{ forloop.counter }}</td>
    <td>{{ attend.staff.first_name }} {{ attend.staff.last_name }}</td>
    <td>{{ attend.enter_time|date:"Y-m-d H:i" }}</td>
    <td>{{ attend.exit_time|date:"Y-m-d H:i" }}</td>
</tr>
{% endfor %}
    </tbody>
</table>

{% endblock %}

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>Dashboard &mdash; Stisla</title>


    <link rel="shortcut icon" href="{% static 'front/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'front/favicon.ico' %}" type="image/x-icon">

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static  'dashboard/modules/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static  'dashboard/modules/fontawesome/css/all.min.css' %}">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{% static  'dashboard/modules/jqvmap/dist/jqvmap.min.css' %}">
  <link rel="stylesheet" href="{% static  'dashboard/modules/summernote/summernote-bs4.css' %}">
  <link rel="stylesheet" href="{% static  'dashboard/modules/owlcarousel2/dist/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static  'dashboard/modules/owlcarousel2/dist/owl.theme.default.min.css' %}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static  'dashboard/css/style.css' %}">
  <link rel="stylesheet" href="{% static  'dashboard/css/components.css' %}">
<!-- Start GA -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script>
<!-- /END GA --></head>

<body>
  <div id="app">
    <div class="main-wrapper main-wrapper-1">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
          </ul>
          <div class="search-element">
            <input class="form-control" type="search" placeholder="Qidirish" aria-label="Search" data-width="250">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>            
          </div>
        </form>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <img alt="image" src="{% static  'dashboard/img/avatar/avatar-1.png' %}" class="rounded-circle mr-1">
            <div class="d-sm-none d-lg-inline-block">Hello, {{user}}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              {% for user in users %}
              <a href="{% url 'dashboard:edit_profile' user.id %}" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profil
              </a>
              {% endfor %}
              <div class="dropdown-divider"></div>
              <a href="{% url 'dashboard:log_out' %}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>
      <div class="main-sidebar sidebar-style-2">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="{% url 'dashboard:index'%}">Stisla</a>
          </div>
          <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li><a href="{% url 'dashboard:index' %}" ><i class="fas fa-home"></i><span>Home</span></a></li>

            <li class="dropdown">
              <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Employee</span></a>
              <ul class="dropdown-menu">
                <li class=><a class="nav-link" href="{% url 'dashboard:create_staff' %}">Add staff</a></li>
                <li ><a class="nav-link" href="{% url 'dashboard:list_staff' %}">Staff list</a></li>
              </ul>
            </li>  
            <li class="dropdown">
              <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>attendance</span></a>
              <ul class="dropdown-menu">
                <li ><a class="nav-link" href="{% url 'dashboard:list_attendance' %}">Staff attendance</a></li>
              </ul>
            </li>    
        </aside>
      </div>

      <!-- Main Content -->
      <div class="main-content">
        {% block content %}
        {% endblock %}
      </div>
      <footer class="main-footer">
        <div class="footer-left">
            &copy; 2024 <div class="bullet"></div> Created by </div>
        <div class="footer-right">
          
        </div>
      </footer>
    </div>
  </div>

  <!-- General JS Scripts -->
  <script src="{% static  'dashboard/modules/jquery.min.js' %}"></script>
  <script src="{% static  'dashboard/modules/popper.js' %}"></script>
  <script src="{% static  'dashboard/modules/tooltip.js' %}"></script>
  <script src="{% static  'dashboard/modules/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static  'dashboard/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static  'dashboard/modules/moment.min.js' %}"></script>
  <script src="{% static  'dashboard/js/stisla.js' %}"></script>
  
  <!-- JS Libraies -->
  <script src="{% static  'dashboard/modules/jquery.sparkline.min.js' %}"></script>
  <script src="{% static  'dashboard/modules/chart.min.js' %}"></script>
  <script src="{% static  'dashboard/modules/owlcarousel2/dist/owl.carousel.min.js' %}"></script>
  <script src="{% static  'dashboard/modules/summernote/summernote-bs4.js' %}"></script>
  <script src="{% static  'dashboard/modules/chocolat/dist/js/jquery.chocolat.min.js' %}"></script>

  <!-- Page Specific JS File -->
  <script src="{% static  'dashboard/js/page/index.js' %}"></script>
  
  <!-- Template JS File -->
  <script src="{% static  'dashboard/js/scripts.js' %}"></script>
  <script src="{% static  'dashboard/js/custom.js' %}"></script>
</body>
</html>

templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}


<section class="section">
  <div class="section-header">
    <h1>Dashboard</h1>
  </div>
  <div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
      <div class="card card-statistic-1">
        <div class="card-icon bg-primary">
          <i class="far fa-user"></i>
        </div>
        <div class="card-wrap">
          <div class="card-header">
            <h4>Adminlar soni</h4>
          </div>
          <div class="card-body">
            {{user}}
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6 col-12">
      <div class="card card-statistic-1">
        <div class="card-icon bg-success">
          <i class="fas fa-circle"></i>
        </div>
        <div class="card-wrap">
          <div class="card-header">
            <h4>Stafflar soni</h4>
          </div>
          <div class="card-body">
            {{staff}}
          </div>
        </div>
      </div>
    </div>                  
  </div>

</section>

{% endblock %}

templates/dashboard/profile.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}

<section class="section">
  <div class="section-header">
    <h1>Profile</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item active"><a href="#">Dashboard</a></div>
      <div class="breadcrumb-item">Profile</div>
    </div>
  </div>
  <div class="section-body">
    <h2 class="section-title">Hello , {{ user.username }}!</h2>

    <div class="row mt-sm-4">
      <div class="col-12 col-md-12 col-lg-7">
        <div class="card">
          <form method="post" class="needs-validation" novalidate="">
            {% csrf_token %}
            <div class="card-header">
              <h4>Edit profile</h4>
            </div>
            <div class="card-body">
              <div class="form-group col-md-6 col-12">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" class="form-control" value="{{ user.username }}" required="">
                <div class="invalid-feedback">
                  Please fill in the username
                </div>
              </div>
              <div class="row">                               
                <div class="form-group col-md-6 col-12">
                  <label for="first_name">Ism</label>
                  <input type="text" id="first_name" name="first_name" class="form-control" value="{{ user.first_name }}" required="">
                  <div class="invalid-feedback">
                    Please fill in the first name
                  </div>
                </div>
                <div class="form-group col-md-6 col-12">
                  <label for="last_name">Familiya</label>
                  <input type="text" id="last_name" name="last_name" class="form-control" value="{{ user.last_name }}" required="">
                  <div class="invalid-feedback">
                    Please fill in the last name
                  </div>
                </div>
              </div>
              <div class="form-group col-md-7 col-12">
                <label for="old_password">Enter old password</label>
                <input type="password" id="old_password" name="old_password" class="form-control" required="">
                <div class="invalid-feedback">
                  Please fill in the password
                </div>
              </div>
              <div class="form-group col-md-7 col-12">
                <label for="new_password">Enter new Password</label>
                <input type="password" id="new_password" name="new_password" class="form-control" value="">
              </div>
              <div class="form-group col-md-7 col-12">
                <label for="confirm_password">Confirm Password</label>
                <input type="password" id="confirm_password" name="confirm_password" class="form-control" value="">
              </div>
            </div>
            <div class="card-footer text-right">
              <button type="submit" class="btn btn-primary">
                Data storage</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/dashboard/staff/create.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}


<section class="section">
  <div class="section-header">
    <h1>Dashboard</h1>
  </div>
<form method="POST">
<div class="form-group">
    <label>Xodim : first_name</label>
    {% csrf_token %}
    <input style='margin-bottom:15px;' type="text" class="form-control" name="first_name">
    <label>Xodim: Last_name</label>
    <input style='margin-bottom:15px;' type="text" class="form-control" name="last_name">
    <button type="submit" class="btn btn-success rounded-pill">Yaratish</button>
</div>
</form>

</section>

{% endblock %}

templates/dashboard/staff/list.html
{% extends "dashboard/base.html" %}
{% block content %}
<br>
<br>
<br>
<table class="table table-striped dataTable no-footer" id="table-1" role="grid" aria-describedby="table-1_info">
    <thead>                                 
      <tr role="row">
        <th class="text-center sorting_asc" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="#: activate to sort column descending">#</th>
        <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1" aria-label="Task Name: activate to sort column ascending">Xodimlar</th>
        <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1" aria-label="Task Name: activate to sort column ascending">Harakatlar</th>
        </thead>
    <tbody>                                 
      
        {% for s in staff %}
        <tr role="row" class="odd">
            <td class="sorting_1">
                {{forloop.counter}}
            </td>
            <td>{{s.first_name}} {{s.last_name}}</td>
            <td> 
                <a href="{% url 'dashboard:update_staff' s.id %}" data-toggle="modal" data-target=".bd-example-modal-lg{{forloop.counter}}" style='margin-right:10px;' ><i class="fas fa-edit"></i>
                </a>
                <button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target=".bd-example-modal-sm{{forloop.counter}}">
                    <i class="fas fa-trash-alt"></i>
                </button>
                <div class="modal fade bd-example-modal-sm{{forloop.counter}}">
                    <div class="modal-dialog modal-sm">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title h4">{{s.first_name}}</h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <i class="anticon anticon-close"></i>
                                </button>
                            </div>
                            <div class="modal-body">
                                <b>{{s.first_name}} ni o`chirmoqchimisiz?</b>
                            </div>
                            <div class="btn-group">
                                <form method="post" action="{% url 'dashboard:delete_staff' s.id %}">
                                    {% csrf_token %}
                                <button type="submit" class="btn btn-primary btn-tone">Ha</button>
                                <button class="btn btn-danger btn-tone" type="button" data-dismiss="modal">Yo`q</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>                
                <div class="modal fade bd-example-modal-lg{{forloop.counter}}">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title h4">{{s.first_name}}</h5>
                                <button type="button" class="close" data-dismiss="modal">
                                    <i class="anticon anticon-close"></i>
                                </button>
                            </div>
                            <form action="{% url 'dashboard:update_staff' s.id %}" method="post">
                                {% csrf_token %}
                            <div class="modal-body">
                                <input type="text" class="form-control" value="{{s.first_name}}" name="first_name" style='margin-bottom:15px;'>
                                <input type="text" class="form-control" value="{{s.last_name}}" name="last_name">
                            </div>
                            <button type="submit" class="btn btn-primary btn-tone" >O`zgartirish</button>
                            </form>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/dashboard/staff/update.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block content %}


<section class="section">
  <div class="section-header">
    <h1>Dashboard</h1>
  </div>
<form method="POST">
<div class="form-group">
    <label>Xodimlar</label>
    {% csrf_token %}
    <input  type="text" class="form-control" name="name" value={{staff.first_name}}>
    <input  type="text" class="form-control" name="name" value={{staff.last_name}}>
    <button type="submit" class="btn btn-success rounded-pill">O'zgartirish</button>
</div>
</form>

</section>
{% endblock %}